### PR TITLE
Puzzle game debug

### PR DESCRIPTION
**Pull request by majdajroudi**
in this PR I fixed a part of the issue #98  

**Problems solved:** 

-  remove double navbar

- display puzzle tiles on the side of the game container for big screen and under the list of images for small screens 

- make images bigger 

- fix responsiveness of the game
Opera Snapshot_2020-11-21_203241_localhost

### CODE REVIEW

**Review by ssinikoglu — APPROVED** [review]
Thanks, code is nice and clean.

**Review by ssinikoglu — COMMENTED** [review]
If it's the only PR for debug Puzzle Game, can you also add a screenshot of it?

**Comment by majdajroudi** [comment]
@ssinikoglu screenshot was added to the PR description

**Review by ssinikoglu — APPROVED** [review]

**Comment by majdajroudi** [comment]
there will be another PR to add the description button but I added the screenshot anyway

**Review by louisrli — APPROVED** [review]

**Pull request merged**
