### PR TITLE
Fix: add all deleted files #72

### PR DESCRIPTION
**Pull request by majdajroudi**
This PR fixes the problem that happened in the morning. I mistakenly deleted few files from Sule's and Tarkan's work, I reverted that commit and added all the files. PTAL #72

### CODE REVIEW

**Comment by louisrli** [comment]
can you please show me the PR where this happened

**Comment by majdajroudi** [comment]
it's the PR #66

**Comment by majdajroudi** [comment]
I pulled the changes from dev and all the changes were staged so I thought I was avoiding duplicates by unstaging those changes but turns out I deleted them, and it wasn't shown in the commit history for me to see those changes

**Review by louisrli — APPROVED** [review]

**Comment by majdajroudi** [comment]
@tmansuroglu @ssinikoglu can you have a look at the files and see if all of your work is here before the PR is merged

**Review by ssinikoglu — APPROVED** [review]

**Comment by tmansuroglu** [comment]
my game files look ok

**Review by tmansuroglu — APPROVED** [review]

**Comment by majdajroudi** [comment]
PR approved, PTAL @Ammar-64

**Pull request merged**
