### PR TITLE
fix resource page styling

### PR DESCRIPTION
**Pull request by YamanSammani**
in this PR, the resource page styling was fixed.

### CODE REVIEW

**Review by louisrli — APPROVED** [review]

**Comment by YamanSammani** [comment]
@Ammar-64 , kindly merge into dev.

**Comment by Ammar-64** [comment]
> @Ammar-64 , kindly merge into dev.

Need another reviewer approve

**Comment by YamanSammani** [comment]
> > @Ammar-64 , kindly merge into dev.
> 
> Need another reviewer approve

Thought Louis approval is above all 😂

**Review by ibrahimaljarad — APPROVED** [review]

**Review by ssinikoglu — APPROVED** [review]

**Comment by YamanSammani** [comment]
@Ammar-64 , done :D

**Pull request merged**
