### PR TITLE
Contact page container #35

### PR DESCRIPTION
**Pull request by ssinikoglu**
This PR consists of container of Contact page.  

ContactUsForm translation files added again, after last merge they were not at the content, but since it's snapshot test is including the translation files there are not any changes for the tests. 

After this PR, there will not add any new features to the page. Next PR's for Contact Page will be about fixing styling and if there is a problem would occur functionality in contact form at debugging phase.

Please review. I am looking forward to your comments.

### CODE REVIEW

**Comment by ssinikoglu** [comment]
Screenshot for large size (1400x580)
localhost_3000_contact_largeScreen

**Comment by ssinikoglu** [comment]
Screenshot for tablet size (768x1024)
localhost_3000_contact_tablet

**Comment by ssinikoglu** [comment]
Screenshot for mobile size (414x736)

**Review by louisrli — APPROVED** [review]

**Review by tmansuroglu — APPROVED** [review]
Nice work!

**Comment by ssinikoglu** [comment]
PR is approved @Ammar-64 , PTL.

**Pull request merged**
