### PR TITLE
Fix Login Pages

### PR DESCRIPTION
**Pull request by YamanSammani**
In this PR: 
1- Facebook and Google Auth were fixed 
2- Login link in the navBar was fixed 
3- Translation key updated. 
4- Background updated.

### CODE REVIEW

**Review by louisrli — COMMENTED** [review]
why were nonworking PRs submitted in the first place? or what exactly is being fixed here? @tmansuroglu

**Comment by YamanSammani** [comment]
> why were nonworking PRs submitted in the first place? or what exactly is being fixed here? @tmansuroglu

Yesterday, both me and Tarkan were working on this branch simultaneously, the Facebook/google auth was working but it seems when we push our updates to the branch it got lost ( myself or Tarkan removed it accidentally, I checked the file changes in the branch and could find a trace to it, so it was not pushing at all).  sorry for any inconvenience this may cause. 
Same for the Login link. if you check the original branch we're working on it "login", you may find both of them there.

**Comment by tmansuroglu** [comment]
> why were nonworking PRs submitted in the first place? or what exactly is being fixed here? @tmansuroglu

Like Yaman said, login methods were working but I think I broke them. Since we didn't have a lot of time I only focused on basic authentication methods and they are working. @louisrli

**Review by louisrli — APPROVED** [review]
exactly why we have code freezes ;)

**Comment by YamanSammani** [comment]
> exactly why we have code freezes ;)

Exactly 😄
I feel I learned github in the last two weeks more than I learned coding 🤣

**Review by majdajroudi — APPROVED** [review]

**Review by tmansuroglu — APPROVED** [review]

**Comment by YamanSammani** [comment]
@Ammar-64 , Kindly merge. Thanks

**Pull request merged**
